name: Python Workflow
on: [push, pull_request]

jobs:
  test:
    name: Testes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Substitua '3.x' pela versão do Python que está utilizando

    - name: Executar testes
      run: |
               python testes.py
